train:
    dataset_name: "semantickitti"
    lr: 0.001
    weight_decay: 1e-3
    save_checkpoint: false
    ignore_label: 0
    checkpoint_path: "/workspace/checkpoints/semanticposs/"

model:
    n_classes: 20
    positions_mode: "xyz"
    values_mode: "none"
    pointnet_channels_per_layer: [16,32]
    pointnet_start_nr_channels: 32
    nr_downsamples: 2
    nr_blocks_down_stage: [1,1,1]
    nr_blocks_bottleneck: 1
    nr_blocks_up_stage: [1,1,1]
    nr_levels_down_with_normal_resnet: 3
    nr_levels_up_with_normal_resnet: 3
    compression_factor: 1.0
    dropout_last_layer: 0.0
    experiment: "none"


lattice_gpu:
    hash_table_capacity: 100000
    nr_sigmas: 1
    sigma_0: "0.9 3"
